/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import static org.example.app.MessageUtils.getMessage;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }

    private static String join(LinkedList tokens) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'join'");
    }

    private static LinkedList split(String message) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'split'");
    }
}
